{%- if cookiecutter.project_template == "standard" %}
{%- include "pyproject-standard.toml" %}
{% endif %}
{%- if cookiecutter.project_template == "nuitka" %}
{%- include "pyproject-nuitka.toml" %}
{%- if cookiecutter.project_template == "cli" %}
{%- include "pyproject-cli.toml" %}
{% endif %}