esphome:
  name: ili9341
esp32:
  # esp32: https://esphome.io/components/esp32.html
  # esp8266: https://esphome.io/components/esp8266.html
  # find boards here:  https://github.com/platformio/platformio-docs/tree/develop/boards
  # wokwi boards here: https://github.com/wokwi/wokwi-boards/tree/main/boards
  board: esp32doit-devkit-v1
debug:
  update_interval: 30s
logger:
  level: debug
spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19
font:
  - file: "gfonts://Roboto"
    id: roboto
    size: 40
display:
  - platform: ili9xxx
    model: ili9341
    dimensions:
      width: 240
      height: 320
    cs_pin: 15
    dc_pin: 2
    reset_pin: 4
    update_interval: 120s
    lambda: |-
      it.print(0, 10, id(roboto), "Hello World!");