[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "{{ cookiecutter.project_name }}"
version = "0.0.1"
{%-if cookiecutter.python_requirements == "exact" %}
requires-python = "== {{ cookiecutter.python }}.*"
{%- else %}
requires-python = "~= {{ cookiecutter.python }}"
{% endif %}
dependencies = [
    "requests",
    "poethepoet"
]

[project.scripts]
{{ cookiecutter.project_name }} = "{{ cookiecutter.project_name }}.main:main"

[tool.poe.tasks]
run = "{{ cookiecutter.project_name }}"