[wokwi]
version = 1
#gdbServerPort = 3333
elf = ".esphome/build/{{ cookiecutter.project_name }}/.pioenvs/{{ cookiecutter.project_name }}/firmware.elf"
firmware = ".esphome/build/{{ cookiecutter.project_name }}/.pioenvs/{{ cookiecutter.project_name }}/firmware.bin"